package cis5550.webserver;

public class Interface {
	public static final String homepage_old = "<!DOCTYPE html>\r\n"
			+ "<html>\r\n"
			+ "<head>\r\n"
			+ "  <title>HOLI Search</title>\r\n"
			+ "  <style>\r\n"
			+ "    /* HOLI title styles */\r\n"
			+ "    .title {\r\n"
			+ "      font-size: 120px;\r\n"
			+ "      font-weight: bold;\r\n"
			+ "      letter-spacing: 30px;\r\n"
			+ "      text-align: center;\r\n"
			+ "      margin-top: 50px;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* HOLI character color styles */\r\n"
			+ "    .h {\r\n"
			+ "      color: #ff4d4d;\r\n"
			+ "    }\r\n"
			+ "    .o {\r\n"
			+ "      color: #ffd633;\r\n"
			+ "    }\r\n"
			+ "    .l {\r\n"
			+ "      color: #4dff4d;\r\n"
			+ "    }\r\n"
			+ "    .i {\r\n"
			+ "      color: #4d4dff;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* Search bar styles */\r\n"
			+ "    .search-container {\r\n"
			+ "      margin-top: 80px;\r\n"
			+ "      display: flex;\r\n"
			+ "      justify-content: center;\r\n"
			+ "      align-items: center;\r\n"
			+ "    }\r\n"
			+ "    input[type=text] {\r\n"
			+ "      width: 50%;\r\n"
			+ "      padding: 12px 20px;\r\n"
			+ "      margin: 8px 0;\r\n"
			+ "      box-sizing: border-box;\r\n"
			+ "      border: 2px solid #ccc;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      font-size: 16px;\r\n"
			+ "    }\r\n"
			+ "    input[type=submit] {\r\n"
			+ "      width: auto;\r\n"
			+ "      background-color: #4CAF50;\r\n"
			+ "      color: white;\r\n"
			+ "      padding: 12px 20px;\r\n"
			+ "      margin: 8px 0;\r\n"
			+ "      border: none;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      cursor: pointer;\r\n"
			+ "      font-size: 16px;\r\n"
			+ "    }\r\n"
			+ "    input[type=submit]:hover {\r\n"
			+ "      background-color: #45a049;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* Search results styles */\r\n"
			+ "    .search-results {\r\n"
			+ "      margin-top: 50px;\r\n"
			+ "      display: flex;\r\n"
			+ "      flex-direction: column;\r\n"
			+ "      align-items: center;\r\n"
			+ "    }\r\n"
			+ "    .result {\r\n"
			+ "      width: 50%;\r\n"
			+ "      background-color: #f2f2f2;\r\n"
			+ "      padding: 20px;\r\n"
			+ "      margin-top: 20px;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.2);\r\n"
			+ "    }\r\n"
			+ "    .result-title {\r\n"
			+ "      font-size: 18px;\r\n"
			+ "      font-weight: bold;\r\n"
			+ "      margin-bottom: 10px;\r\n"
			+ "    }\r\n"
			+ "    .result-url {\r\n"
			+ "      font-size: 14px;\r\n"
			+ "      color: #0066cc;\r\n"
			+ "      margin-bottom: 10px;\r\n"
			+ "    }\r\n"
			+ "  </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "  <!-- HOLI title -->\r\n"
			+ "  <div class=\"title\">\r\n"
			+ "    <span class=\"h\">H</span>\r\n"
			+ "    <span class=\"o\">O</span>\r\n"
			+ "    <span class=\"l\">L</span>\r\n"
			+ "    <span class=\"i\">I</span>\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <!-- Search bar -->\r\n"
			+ "  <div class=\"search-container\">\r\n"
			+ "    <form id=\"search-form\">\r\n"
			+ "      <input type=\"text\" placeholder=\"Search...\" name=\"query\">\r\n"
			+ "      <input type=\"submit\" value=\"Search\">\r\n"
			+ "    </form>\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <!-- Search results section -->\r\n"
			+ "  <div class=\"search-results\" id=\"search-results\">\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <!-- Script to handle form submission -->\r\n"
			+ "  <script>\r\n"
			+ "    const form = document.getElementById('search-form');\r\n"
			+ "    form.addEventListener('submit', function(event) {\r\n"
			+ "      event.preventDefault();\r\n"
			+ "      const query = form.elements.query.value;\r\n"
			+ "      const url = `http://localhost:8080/search?q=${query}`;\r\n"
			+ "      fetch(url)\r\n"
			+ "        .then(response => response.json())\r\n"
			+ "        .then(data => {\r\n"
			+ "          const resultsDiv = document.getElementById('search-results');\r\n"
			+ "				resultsDiv.innerHTML = ''; // Clear previous results\r\n"
			+ "\r\n"
			+ "            for (const result of data) {\r\n"
			+ "              const resultElem = document.createElement('div');\r\n"
			+ "              resultElem.classList.add('result');\r\n"
			+ "\r\n"
			+ "              const titleElem = document.createElement('h2');\r\n"
			+ "              titleElem.textContent = result.title;\r\n"
			+ "              resultElem.appendChild(titleElem);\r\n"
			+ "\r\n"
			+ "              const textElem = document.createElement('p');\r\n"
			+ "              textElem.innerHTML = `<a href=\"${result.url}\">${result.url}</a>`;\r\n"
			+ "              resultElem.appendChild(textElem);\r\n"
			+ "\r\n"
			+ "              resultsDiv.appendChild(resultElem);"
			+ "				}\r\n"
			+ "          })\r\n"
			+ "          .catch(error => {\r\n"
			+ "            console.error('Error:', error);\r\n"
			+ "            resultsDiv.textContent = 'An error occurred. Please try again later.';\r\n"
			+ "          });\r\n"
			+ "      });\r\n"
			+ "    </script>\r\n"
			+ "  </body>\r\n"
			+ "</html>\r\n"
			+ "\r\n"
			+ "";
	public static final String homepage = "<!DOCTYPE html>\r\n"
			+ "<html>\r\n"
			+ "<head>\r\n"
			+ "  <title>HOLI Search</title>\r\n"
			+ "  <style>\r\n"
			+ "    /* HOLI title styles */\r\n"
			+ "    .title {\r\n"
			+ "      font-size: 120px;\r\n"
			+ "      font-weight: bold;\r\n"
			+ "      letter-spacing: 30px;\r\n"
			+ "      text-align: center;\r\n"
			+ "      margin-top: 50px;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* HOLI character color styles */\r\n"
			+ "    .h {\r\n"
			+ "      color: #ff4d4d;\r\n"
			+ "    }\r\n"
			+ "    .o {\r\n"
			+ "      color: #ffd633;\r\n"
			+ "    }\r\n"
			+ "    .l {\r\n"
			+ "      color: #4dff4d;\r\n"
			+ "    }\r\n"
			+ "    .i {\r\n"
			+ "      color: #4d4dff;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* Search bar styles */\r\n"
			+ "    .search-container {\r\n"
			+ "      margin-top: 80px;\r\n"
			+ "      display: flex;\r\n"
			+ "      justify-content: center;\r\n"
			+ "      align-items: center;\r\n"
			+ "    }\r\n"
			+ "    input[type=text] {\r\n"
			+ "      width: 50%;\r\n"
			+ "      padding: 12px 20px;\r\n"
			+ "      margin: 8px 0;\r\n"
			+ "      box-sizing: border-box;\r\n"
			+ "      border: 2px solid #ccc;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      font-size: 16px;\r\n"
			+ "    }\r\n"
			+ "    input[type=submit] {\r\n"
			+ "      width: auto;\r\n"
			+ "      background-color: #4CAF50;\r\n"
			+ "      color: white;\r\n"
			+ "      padding: 12px 20px;\r\n"
			+ "      margin: 8px 0;\r\n"
			+ "      border: none;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      cursor: pointer;\r\n"
			+ "      font-size: 16px;\r\n"
			+ "    }\r\n"
			+ "    input[type=submit]:hover {\r\n"
			+ "      background-color: #45a049;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    /* Search results styles */\r\n"
			+ "    .search-results {\r\n"
			+ "      margin-top: 50px;\r\n"
			+ "      display: flex;\r\n"
			+ "      flex-direction: column;\r\n"
			+ "      align-items: center;\r\n"
			+ "    }\r\n"
			+ "    .result {\r\n"
			+ "      width: 50%;\r\n"
			+ "      background-color: #f2f2f2;\r\n"
			+ "      padding: 20px;\r\n"
			+ "      margin-top: 20px;\r\n"
			+ "      border-radius: 4px;\r\n"
			+ "      box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.2);\r\n"
			+ "    }\r\n"
			+ "    .result-title {\r\n"
			+ "      font-size: 18px;\r\n"
			+ "      font-weight: bold;\r\n"
			+ "      margin-bottom: 10px;\r\n"
			+ "    }\r\n"
			+ "    .result-url {\r\n"
			+ "      font-size: 14px;\r\n"
			+ "      color: #0066cc;\r\n"
			+ "      margin-bottom: 10px;\r\n"
			+ "    }\r\n"
			+ "  </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "  <!-- HOLI title -->\r\n"
			+ "  <div class=\"title\">\r\n"
			+ "    <span class=\"h\">H</span>\r\n"
			+ "    <span class=\"o\">O</span>\r\n"
			+ "    <span class=\"l\">L</span>\r\n"
			+ "    <span class=\"i\">I</span>\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <!-- Search bar -->\r\n"
			+ "  <div class=\"search-container\">\r\n"
			+ "    <form id=\"search-form\">\r\n"
			+ "      <input type=\"text\" placeholder=\"Search...\" name=\"query\">\r\n"
			+ "      <input type=\"submit\" value=\"Search\">\r\n"
			+ "    </form>\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <!-- Search results section -->\r\n"
			+ "  <div class=\"search-results\" id=\"search-results\">\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "  <div class=\"pagination-container\">\r\n"
			+ "    <ul class=\"pagination\"></ul>\r\n"
			+ "  </div>\r\n"
			+ "\r\n"
			+ "<script>\r\n"
			+ "    function getQuery() {\r\n"
			+ "        return form.elements.query.value;\r\n"
			+ "      }\r\n"
			+ "    const form = document.getElementById('search-form');\r\n"
			+ "    const resultsDiv = document.getElementById('search-results');\r\n"
			+ "    const paginationDiv = document.getElementById('pagination');\r\n"
			+ "      function handlePaginationClick(event) {\r\n"
			+ "        event.preventDefault();\r\n"
			+ "        const query = form.elements.query.value;\r\n"
			+ "        // const page = event.target.dataset.page;\r\n"
			+ "        // console.log(page)\r\n"
			+ "        // const url = `http://localhost:8080/search?q=${query}&p=${page}`;\r\n"
			+ "        fetch(event.target.href)\r\n"
			+ "            .then(response => response.json())\r\n"
			+ "            .then(data => renderSearchResults(data))\r\n"
			+ "            .catch(error => {\r\n"
			+ "                console.error(\"Error:\", error);\r\n"
			+ "            });\r\n"
			+ "      }\r\n"
			+ "\r\n"
			+ "      function generatePagination(currentPage, totalPages) {\r\n"
			+ "        const paginationContainer = document.createElement('div');\r\n"
			+ "        paginationContainer.classList.add('pagination');\r\n"
			+ "\r\n"
			+ "        if (currentPage > 1) {\r\n"
			+ "            const prevLink = document.createElement('a');\r\n"
			+ "            prevLink.href = `http://localhost:8080/search?q=${getQuery()}&p=${currentPage - 1}`;\r\n"
			+ "            prevLink.textContent = 'Prev';\r\n"
			+ "            prevLink.addEventListener('click', handlePaginationClick);\r\n"
			+ "            paginationContainer.appendChild(prevLink);\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        const startPage = Math.max(currentPage - 2, 1);\r\n"
			+ "        const endPage = Math.min(currentPage + 2, totalPages);\r\n"
			+ "\r\n"
			+ "        for (let i = startPage; i <= endPage; i++) {\r\n"
			+ "            const pageLink = document.createElement('a');\r\n"
			+ "            pageLink.href = `http://localhost:8080/search?q=${getQuery()}&p=${i}`;\r\n"
			+ "            pageLink.textContent = i;\r\n"
			+ "            if (i === currentPage) {\r\n"
			+ "                pageLink.classList.add('active');\r\n"
			+ "            } else {\r\n"
			+ "                pageLink.addEventListener('click', handlePaginationClick);\r\n"
			+ "            }\r\n"
			+ "            paginationContainer.appendChild(pageLink);\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        if (currentPage < totalPages) {\r\n"
			+ "            const nextLink = document.createElement('a');\r\n"
			+ "            nextLink.href = `http://localhost:8080/search?q=${getQuery()}&p=${currentPage + 1}`;\r\n"
			+ "            nextLink.textContent = 'Next';\r\n"
			+ "            nextLink.addEventListener('click', handlePaginationClick);\r\n"
			+ "            paginationContainer.appendChild(nextLink);\r\n"
			+ "        }\r\n"
			+ "        return paginationContainer;\r\n"
			+ "      }\r\n"
			+ "\r\n"
			+ "      function renderSearchResults(data) {\r\n"
			+ "        const resultsDiv = document.getElementById('search-results');\r\n"
			+ "        resultsDiv.innerHTML = '';\r\n"
			+ "\r\n"
			+ "        for (const result of data.results) {\r\n"
			+ "            const resultElem = document.createElement('div');\r\n"
			+ "            resultElem.classList.add('result');\r\n"
			+ "\r\n"
			+ "            const titleElem = document.createElement('h2');\r\n"
			+ "            titleElem.textContent = result.title;\r\n"
			+ "            resultElem.appendChild(titleElem);\r\n"
			+ "\r\n"
			+ "            const textElem = document.createElement('p');\r\n"
			+ "            textElem.innerHTML = `<a href=\"${result.url}\">${result.url}</a>`;\r\n"
			+ "            resultElem.appendChild(textElem);\r\n"
			+ "\r\n"
			+ "            resultsDiv.appendChild(resultElem);\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        const pagination = generatePagination(data.page, data.totalPages);\r\n"
			+ "        resultsDiv.appendChild(pagination);\r\n"
			+ "      }\r\n"
			+ "\r\n"
			+ "      \r\n"
			+ "\r\n"
			+ "      form.addEventListener('submit', function(event) {\r\n"
			+ "        event.preventDefault();\r\n"
			+ "        const query = form.elements.query.value;\r\n"
			+ "        const url = `http://localhost:8080/search?q=${query}&p=1`;\r\n"
			+ "        fetch(url)\r\n"
			+ "            .then(response => response.json())\r\n"
			+ "            .then(data => renderSearchResults(data))\r\n"
			+ "            .catch(error => {\r\n"
			+ "                console.error(\"Error:\", error);\r\n"
			+ "                // resultsDiv.textContent = \"An error occurred. Please try again later.\";\r\n"
			+ "            });\r\n"
			+ "      });\r\n"
			+ "      \r\n"
			+ "    </script>\r\n"
			+ "  </body>\r\n"
			+ "</html>";
}
